name: my_school
description: "A new My School Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
#  docker_commander: ^2.1.6
  get: 4.6.6
  flutter:
    sdk: flutter
  #  Cupertino Icons
  cupertino_icons: ^1.0.8

  #  Email Validator
  email_validator: ^3.0.0

  #  http package
  http: ^1.2.1

  #  SVG Image
  flutter_svg: ^2.0.10+1

  #  Shared Preference
  shared_preferences: ^2.2.3

  #  Date Format
  intl: ^0.19.0

  #  PostGreSql
  postgres: ^3.2.1
#  postgres: ^2.2.0

#  flutter_svg_provider: ^1.0.7
#  flutter_svg: ^1.0.0

#  animated sidebar

  animated_sidebar: ^1.0.1
  image_picker: ^1.1.2
  file_picker: ^8.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/svg/
    - assets/teacherinformation.json
    - assets/studentinformation.json
    - assets/add_student_attendance.json
    - assets/timetable.json
    - assets/allclasses.json
    - assets/subject.json
    - assets/Images/schoolEvent/school_event_image.jpg
    - assets/newtimetable.json
    - assets/homework.json
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
